function [Protein, RNA, Lectin] = InitiateSpecies()
    % This function initializes and returns tables and arrays for protein, RNA, and
    % lectin species used in the analysis. It includes protein names with their 
    % possible sialylated sites, RNA types, and lectin details with corresponding 
    % concentration values.
    % Outputs:
    %   Protein - Table containing protein names and possible sialylated sites
    %   RNA - Array of RNA types
    %   Lectin - Table containing lectin types, their concentrations, and associated protein values
    
    % Define protein names and their possible sialylated sites
    Protein = [...
        "ACE2";...
        "Fetuin";...
        "GYPA";...
        "LAMP1";...
        "NXST-b.V1x1";...
        "NXST-m.V1x1";...
        "NXST-m.V1x2";...
        "NXST-m.V2x1";...
        "tdPP7-b";...
        "tdPP7-m"...
        ];
    % Possible sialylated sites corresponding to each protein
    SA_sites = [7+2, 2+2, 13+2, 19+2, 0, 5+2, 10+2, 5+2, 0, 0+2];
    % Create a table for proteins with their names and possible sialylated sites
    Protein = table(Protein, SA_sites', 'VariableNames', ["Name", "PossibleSialylatedSites"]);
    
    % Define RNA types
    RNA = ["-"; "8"];
    
    % Define lectin details including sign, concentration, and Lectin2Protein values
    Lectin = table(...
        ["-"; string(9:-1:0)'],... % Sign of the lectin
        (2 * [0, 0.5.^(9:-1:0)]'),... % Concentration values of the lectin
        round(5.6 * [0, 0.5.^(9:-1:0)]', 2),... % Lectin2Protein values rounded to 2 decimal places
        'VariableNames', ["Sign", "Concentration", "Lectin2Protein"]...
        );

end % function
